// Pro signing PUBLIC key — safe to commit and ship (verifies keys, cannot mint them).
// AUTO-GENERATED by scripts/gen-pro-keypair.mjs. To rotate: delete .secrets/pro-private.jwk and re-run.
export const PRO_PUBLIC_JWK = {"key_ops":["verify"],"ext":true,"kty":"EC","x":"t1WUHOM5XTYntnL2HhX8JBnkUBPCaCnkxSCn5EvPRZs","y":"IOGjLeAOf6FSax_iuKOoRfbYT-PwooR1cZvRqvJ19WA","crv":"P-256"};
